### ISSUE TITLE
FB00000??? for Halgrimson & co

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#21]
@robes commented on [Wed Mar 22 2017](https://github.com/informatics-isi-edu/facebase-project/issues/290)

Working with Rajiv Parma.

This is the dataset that requires a new Project entry for a non-Spoke where the PIs are also Spoke PIs.

**Comment by bugacov** [comment]
Just entered issue #23 to track this submission (FB00000875). I'm closing this issue.
