### ISSUE TITLE
Spritz Human subject data FB00000861 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#38]
This dataset will replace all other Spritz datasets 862,863,873,874,876,877. 
A new data transfer will happen next week were they will add some missing metadata like syndrome. That data will replace what's currently under 861 and all other datasets will be removed. From then on there will be a single dataset (FB00000861) for this data and on each monthly data transfer we will update the metadata for each sample (subject) to the latest value and add new files to that sample if any.

**Comment by bugacov** [comment]
I delete the datasets FB00000862,863,873,874,876,877 from the catalog since they will all be consolidated into 861 once we receive the new data from Rajiv. Also updated the title, summary and description of 861.

**Comment by bugacov** [comment]
861 was curated with initial set of data before the annual mtg. 
Some modification to the data (adding gene field) is pending so will leave this issue opened in curate to make the changes when we receive the updated data.

**Comment by crisaless** [comment]
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=TJ0

Nothing for gene field so looks like spritz group still needs to send info

**Comment by bugacov** [comment]
This was done. Closing.
