### ISSUE TITLE
FB00000885 3D model objects update for Fisher lab

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#4]
@robes commented on [Wed Mar 22 2017](https://github.com/informatics-isi-edu/facebase-project/issues/291)

Not sure which dataset AN this corresponds with. Currently, we are just working out the rendering of the 3D surface meshes before getting serious about updating the dataset.

**Comment by bugacov** [comment]
Loaded the obj meshes  received from Azman for the Exp#11 Fish2 dataset to the viz.mesh table

**Comment by robes** [comment]
The objects are ready for review here

https://dev.facebase.org/data/record/#1/isa:dataset/id=14123

But we may not have a way to test these since hatrac/ermrest don't support CORS and we haven't setup the data volume a copy-on-write mirror of the production store.
