### ISSUE TITLE
FB00000<TBD> (GEO data from YC)

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#42]
This is the more recent GEO related dataset. This probably does not have an ACC number yet.

We have the data and (geo) spreadsheet here:

data-staging:/home/vasu/GSE93333_*

**Comment by crisaless** [comment]
any way of identifying this dataset?

**Comment by BridgetDS** [comment]
We already have uploaded datasets with that geo number. Can close.
