### ISSUE TITLE
FB00000891: New requested custom microarray data from Joan Hoper

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#43]

**Comment by robes** [comment]
@bugacov So there are only 2 files, and none of the assays have files? Its an odd dataset.

**Comment by bugacov** [comment]
Yes. It's an odd dataset. the array data is in a strange txt file format
which is the result of some analysis but she said that this was a bit of a
custom experiment and the raw data files wouldn't make much sense.
I asked her about whether there should be any sort of associated
visualization
but she said no.
We should prob. schedule a call with her to see what else should be done to
this dataset.

**Comment by crisaless** [comment]
This dataset was released - it has a few QC issues but is available to public:

https://www.facebase.org/chaise/record/#1/isa:dataset/RID=TK4

**Comment by bugacov** [comment]
@robes .... what's your thought on this regarding QC issues? 
I would say we should close these issues and then come up w/ a strategy on how to address the issues that were created by the QC system.

**Comment by robes** [comment]
yes
