### ISSUE TITLE
thumbnails for FB00000890 and related datasets

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#46]
I believe there are more thumbnails for FB00000890 and related datasets from Fisher lab.

**Comment by crisaless** [comment]
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=V04

26 thumbnails but don't know about related datasets

**Comment by bugacov** [comment]
We should close this one and leave #46 opened and check if there are additional thumbnails available that were not uploaded.
