### ISSUE TITLE
FB00000861: Delete some LA subject entries from dataset  

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#48]
SubjectID LA0111_1.  
This subject wishes to be removed from the study.  This subject needs to be removed from the metadata and the corresponding images need to be removed.  The metadata-to-image key is in: scansub_Jan.csv uploaded in the January data upload.  The corresponding images to be removed are:
160303110955.ply

160303111016.ply
160303111056.ply

They also want several subjects removed due to poor picture quality.  These aren't on the fileserver anymore, and aren't in the metadata-to-image keys that have been uploaded.  So I don't know what the image file names for these are, and if they have been uploaded to the hub.  
But these subjects appear in the metadata uploaded.  Can you remove them.  They are SubjectID's:
- LA0013_1
- LA0020_01
- LA0021_1
- LA0046_1
- LA0047_1
- LA0050_1 to LA0053_1
- LA0055_1
- LA0056_1
- LA0080_1
- LA0081 to LA0085, but these don't look to have been in the metadata uploaded to the hub anyways

There looks to be images uploaded for LA0020_01.  They want these removed.  The images files (from looking at the scansub key) are:
150914114249.ply
150914114308.ply
150914114347.ply
150914114402.ply

**Comment by crisaless** [comment]
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=TJ0

Seems like this one would be important to finish up (if it's not done already)

**Comment by bugacov** [comment]
This data has changed since then so can be closed.
