### ISSUE TITLE
FB00000893: Issue to track the submission of enhancer data requested by Iros from Vissel's group

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#52]
Sent accessioned spreadsheet on 06/14/17

**Comment by bugacov** [comment]
This submission was requested by Iros but then Caylin said that she will take over the submission from Iros and was supposed to enter it using the self curation tools. She entered several datasets but based on the metadata spreadsheet that she shared with us (email from Nov 1st) it doesn't seem like this one was entered. 
So this dataset will be entered via self-curation and change its accession number.

**Comment by crisaless** [comment]
@bugacov seems like this could be closed if the dataset was entered under a different accession number?

**Comment by bugacov** [comment]
Yes. this can be closed.
