### ISSUE TITLE
Correct attribution on Visel datasets

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#53]
See attached spreadsheet. Fields that need to be updated are highlighted.

**Comment by robes** [comment]
This is the revised and current spreadsheet for the needed changes.
[FaceBase_Data_CS_AV02.xlsx](https://github.com/informatics-isi-edu/facebase-curation/files/1113592/FaceBase_Data_CS_AV02.xlsx)

**Comment by robes** [comment]
@bugacov Can you please prioritize this to the top of the stack on Monday?

**Comment by bugacov** [comment]
This been done and currently in dev machine

**Comment by robes** [comment]
OK. From what I can see by looking over the spreadsheet and comparing to a CSV downloaded from the dev machine, it seems to be correct. Ready to go.
