### ISSUE TITLE
Fix funding for Yang's FB1 datasets

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#65]
This was reported by Steven today. Yang will contact us with correct values.

**Comment by bugacov** [comment]
Here's the spreadsheet with changes that Bridget indicated for this issue

[yang_chai_fb1_funding.xlsx](https://github.com/informatics-isi-edu/facebase-curation/files/1212406/yang_chai_fb1_funding.xlsx)

**Comment by bugacov** [comment]
These changes are now  done on dev

**Comment by robes** [comment]
I could just review a sampling of them. The ones I checked looked correct.
