### ISSUE TITLE
FB00000864, 65, 66 are missing the experiment type

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/facebase-curation#68]
They all use the legacy "data type" annotation when they should use the "experiment type". These all look like _hard tissue_ CT.

**Comment by bugacov** [comment]
I tagged them us hard tissue microCT but would be good to confirm w/ scientist if the term make sense for their data

**Comment by crisaless** [comment]
These are the datasets - has fisher or harris been consulted about the experiment type?

https://www.facebase.org/chaise/record/#1/isa:dataset/RID=VHT
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=VF2
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=VA6

**Comment by bugacov** [comment]
Yes. In fact those terms don't exists any more. This can be closed.
