### ISSUE TITLE
Transfer 3 datasets created by Maas group on dev machine to production

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#72]
-- also add linking of clinical_assay to actual files. this info still needs to be provided by Victoria

**Comment by bugacov** [comment]
These were 921, 922 and 923

**Comment by crisaless** [comment]
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=26V4
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=26V8
https://www.facebase.org/chaise/record/#1/isa:dataset/RID=26VC

Multiple QC issues

**Comment by bugacov** [comment]
Done
