### ISSUE TITLE
Move files of FB00000917 out of production and into the human-subject machine

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/facebase-curation#73]
- [x] remove files from hatrac

- [x] for the time being leave link as we did with 807.2

- [x] package them and move them to the new human-subject machine

**Comment by bugacov** [comment]
The file are removed from hatrac and move to /facebase/FB2_DATASETS/FB00000917 on fb-hsubject-prod machine. Please review on www and then we need to switch status back to curated.

**Comment by crisaless** [comment]
This datasets is out on production: https://www.facebase.org/chaise/record/#1/isa:dataset/RID=26HG

**Comment by bugacov** [comment]
This is done
